kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kubepi-pvc
  labels:
    app: kubepi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
