apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-postgresql
  namespace: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab-postgresql
  template:
    metadata:
      labels:
        app: gitlab-postgresql
    spec:
      containers:
      - name: postgresql
        image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/postgres:17.4
        env:
        - name: POSTGRES_PASSWORD
          value: "gitlab-postgres"
        - name: POSTGRES_USER
          value: "gitlab"
        - name: POSTGRES_DB
          value: "gitlabhq_production"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
          subPath: data
      volumes:
      - name: postgresql-data
        persistentVolumeClaim:
          claimName: gitlab-postgres-pvc
