apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: harbor.vcloud.pub/docker.io/gitlab/gitlab-ce:latest
        env:
        - name: GITLAB_OMNIBUS_CONFIG
          value: |
            external_url 'http://gitlab.k8s.kld.cn'
            gitlab_rails['db_adapter'] = 'postgresql'
            gitlab_rails['db_encoding'] = 'unicode'
            gitlab_rails['db_host'] = 'postgresql'
            gitlab_rails['db_port'] = '5432'
            gitlab_rails['db_username'] = 'gitlab'
            gitlab_rails['db_password'] = 'passw0rd'
            gitlab_rails['redis_host'] = 'redis'
            gitlab_rails['redis_port'] = '6379'
            gitlab_rails['gitlab_shell_ssh_port'] = 22
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 22
        resources:
          requests:
            cpu: "1000m"       # 1 CPU core
            memory: "2Gi"       # 2GB RAM
          limits:
            cpu: "2000m"        # 2 CPU cores
            memory: "4Gi"       # 4GB RAM
        volumeMounts:
        - name: gitlab-data
          mountPath: /var/opt/gitlab
        - name: gitlab-config
          mountPath: /etc/gitlab
        - name: gitlab-logs
          mountPath: /var/log/gitlab
      volumes:
      - name: gitlab-data
        persistentVolumeClaim:
          claimName: gitlab-pvc
      - name: gitlab-config
        persistentVolumeClaim:
          claimName: gitlab-config-pvc
      - name: gitlab-logs
        persistentVolumeClaim:
          claimName: gitlab-logs-pvc
